server:
  port: 80
   
#配置jdbc连接数据库信息
spring:  datasource:    url: jdbc:mysql://localhost:3306/mysql0504
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
#配置mybatis-plus
mybatis-plus:  type-aliases-package: com.lingyi.app.bean
  check-config-location: false
  configuration:    auto-mapping-behavior: partial
  global-config:    db-config:      db-type: mysql
      id-type: auto
#配置mybatis-sql日志
logging:  level:    com:
      lingyi:
          app:
            mapper: TRACE

